ereceipt/ereceipt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('administrator.urls')),
]

ereceipt/main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include(([
        path('', views.home, name='home'),
        path('contribute', views.contribute, name="contribute"),
        path('access', views.access, name="access"),
        path('about', views.about, name="about"),
        path('verify', views.verify, name="verify"),
        path('receipt/<int:student_id>', views.receipt, name="receipt"),
        # path('import', views.import_excel, name="import"),
    ], 'ereceipt'), namespace='main')),
]

ereceipt/main/models.py
# import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# Create variables to store user types
SUPER_ADMIN = 1
STUDENT = 2

USERTYPE_CHOICES = (
    (SUPER_ADMIN, 'Administrator'),
    (STUDENT, 'Student'), 
)

# Create variables to store payment status
PAID = 1
UNPAID = 0

PAYMENT_STATUS = (
    (PAID, 'Paid'),
    (UNPAID, 'Not-Paid'), 
)

class User(AbstractUser):
    # Add User type
    user_type = models.PositiveSmallIntegerField(choices=USERTYPE_CHOICES, default=STUDENT)

    REQUIRED_FIELDS = ['first_name', 'last_name', 'email', 'user_type']


# Model for landlords
class Student(models.Model):
    FullName = models.CharField(max_length=100, null=True)
    MatricNo = models.CharField(max_length=30, null=True, blank=True)
    Level = models.CharField(max_length=15, null=True, blank=True)
    Paid = models.PositiveSmallIntegerField(choices=PAYMENT_STATUS, default=UNPAID)
    Amount = models.FloatField('Amount Paid', max_length=40, null=True, blank=True)
    Date = models.DateField('Payment Date', default=timezone.now, null=True, blank=True)
    ReceiptNo = models.CharField(max_length=30, unique=True, null=True, blank=True)

    def __str__(self):
        return self.FullName
    

ereceipt/main/views.py
import pandas as pd
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from .models import Student

# Create your views here.
def home(request):
    return render(request, 'main/home.html')

def contribute(request):
    return render(request, 'main/contribute.html')

def access(request):
    return render(request, 'main/access.html')

def about(request):
    return render(request, 'main/about.html')

def verify(request):
    if request.method == "POST":
        # Get Matric Number
        MatricNo = request.POST.get('MatricNo')
        if MatricNo is None:
            messages.error(request, 'No Matric/Jamb Number')
            return HttpResponseRedirect(reverse("main:verify"))
        else:
            try:
                student = Student.objects.get(MatricNo=MatricNo)
                if student.Paid == 1:
                    # Payment is verified
                    return redirect('main:receipt', student_id=student.id)
                else:
                    messages.error(request, 'Payment Not Yet Verified, Try again later ')
                    return HttpResponseRedirect(reverse("main:verify")) 
            except ObjectDoesNotExist:
                messages.error(request, 'Something Went Wrong')
                return HttpResponseRedirect(reverse("main:verify"))
            
    return render(request, 'main/verify.html')

def receipt(request, student_id):
    try:
        student = Student.objects.get(id=student_id)
        return render(request, 'main/receipt.html', {'student': student})
    except ObjectDoesNotExist:
        messages.error(request, 'Something Went Wrong')
        return HttpResponseRedirect(reverse("main:verify"))

# def import_excel(request):
#     if request.method == "POST" and request.FILES["csv_file"]:
#         data = request.FILES["csv_file"]

#         if data.name.endswith(".csv"):
#             # Read the Excel file using pandas
#             df = pd.read_csv(data)

#             # Loop through the DataFrame and create Student objects
#             for index, row in df.iterrows():
#                 student = Student(
#                     FullName=row["FullName"],
#                     MatricNo=row["MatricNo"],
#                     Level=row["Level"]
#                 )
#                 student.save()

#     return render(request, "main/import_excel.html")

ereceipt/main/templates/main/about.html
{% extends 'index.html' %}
{% load static %}

{% block title %}About{% endblock title %}

{% block top %} 
<ul class="navbar-nav mx-auto">
    <li class="nav-item"><a class="nav-link" href="{% url 'main:home' %}">Home</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:contribute' %}">Contribute</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:access' %}">Access</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:verify' %}">Verify</a></li>
    <li class="nav-item"><a class="nav-link active" href="{% url 'main:about' %}">About</a></li>
</ul><a class="btn btn-primary shadow" role="button" href="{% url 'main:verify' %}" style="background: #03123E;border-radius: 20px;box-shadow: 0px 0px #4A524D;">E-Receipt</a>
{% endblock top %}

{% block header  %}
    <section class="py-2 mt-2">
        <div class="container py-4 py-xl-3">
            <div class="row gy-4 gy-md-0">
                <div class="col-md-6 text-center text-md-start d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                    <div style="max-width: 350px;">
                        <h1 class="display-5 fw-bold mb-4">About&nbsp;<span class="underlined">C.A.R.E.S</span></h1>
                        <p class="text-muted my-4">This is an initiative of the Redeemers University Accounting Student 
                            Association (RUNASA) 2023/2024 Executives.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div><img class="rounded img-fluid w-100 fit-cover" style="min-height: 150px;" src="{% static 'img/illustrations/startup.svg' %}"></div>
                </div>
            </div>
        </div>
    </section>
{% endblock header  %}

{% block section1 %}
<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-5">
                <h4 class="fw-bold">What is C.A.R.E.S ?</h4>
            </div>
            <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5"> 
                <p>The Collaborative Academic Resource Exchange System (CARES), is an of the 
                    Redeemer's University Accounting Student Association (RUNASA) 
                    executives and the Academic Committee of the department!</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 mb-5">
                <h4 class="fw-bold">Why C.A.R.E.S ?</h4>
            </div>
            <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5"> 
                <p>This initiative aims to create a centralized repository of essential course materials 
                    and past questions, ensuring that all students have easy access to the resources they 
                    need to excel academically. By contributing your materials, you're not only helping 
                    fellow students but also fostering a collaborative learning environment within the 
                    department.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 mb-5">
                <h4 class="fw-bold">E-Receipt</h4>
            </div>
            <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5"> 
                <p>E-Receipt is our digital solution to simplify payment tracking and record-keeping 
                    for students in the department. Our system enables quick and secure access to 
                    electronic receipts for verified transactions, providing a convenient and 
                    eco-friendly way to manage payments.</p>
            </div>
        </div>
    </div>
</section>
{% endblock section1 %}

ereceipt/main/templates/main/access.html
{% extends 'index.html' %}
{% load static %}

{% block title %}Access{% endblock title %}

{% block top %} 
<ul class="navbar-nav mx-auto">
    <li class="nav-item"><a class="nav-link" href="{% url 'main:home' %}">Home</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:contribute' %}">Contribute</a></li>
    <li class="nav-item"><a class="nav-link active" href="{% url 'main:access' %}">Access</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:verify' %}">Verify</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:about' %}">About</a></li>
</ul><a class="btn btn-primary shadow" role="button" href="{% url 'main:verify' %}" style="background: #03123E;border-radius: 20px;box-shadow: 0px 0px #4A524D;">E-Receipt</a>
{% endblock top %}

{% block header  %}
    <section class="py-5 mt-5">
        <div class="container py-4 py-xl-5">
            <div class="row gy-4 gy-md-0">
                <div class="col-md-6 text-center text-md-start d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                    <div style="max-width: 350px;">
                        <h1 class="display-5 fw-bold mb-4">Under&nbsp;<span class="underlined">Development</span></h1>
                        <p class="text-muted my-4">The repository is currently in development. Once completed you can access a plethora of course materials and past questions, as well other documents to help you excel academically.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div><img class="rounded img-fluid w-100 fit-cover" style="min-height: 300px;" src="{% static 'img/illustrations/startup.svg' %}"></div>
                </div>
            </div>
        </div>
    </section>
{% endblock header  %}
    

ereceipt/main/templates/main/home.html
{% extends 'index.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block top %} 
<ul class="navbar-nav mx-auto">
    <li class="nav-item"><a class="nav-link active" href="{% url 'main:home' %}">Home</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:contribute' %}">Contribute</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:access' %}">Access</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:verify' %}">Verify</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:about' %}">About</a></li>
</ul><a class="btn btn-primary shadow" role="button" href="{% url 'main:verify' %}" style="background: #03123E;border-radius: 20px;box-shadow: 0px 0px #4A524D;">E-Receipt</a>
{% endblock top %}

{% block header %}
<header class="pt-5">
    <div class="container pt-4 pt-xl-5">
        <div class="row pt-5">
            <div class="col-md-8 text-center text-md-start mx-auto">
                <div class="text-center">
                    <h1 class="display-4 fw-bold pulse animated infinite mb-5" style="color: #03123E;">Collaborative Academic Resource&nbsp;<span class="underlined" style="color: #03123E;">Exchange</span>.</h1>
                    <p class="fs-5 text-muted tada animated mb-5">Sponsored by Redeemer's University Accounting Student Association (RUNASA)&nbsp;</p>
                </div>
            </div>
            <div class="col-12 col-lg-10 mx-auto">
                <div class="text-center position-relative"><img class="img-fluid" src="{% static 'img/illustrations/data-management.svg' %}" style="width: 800px;"></div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}

{% block section1 %}
    <section>
        <div class="container py-4 py-xl-5">
            <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-lg-3">
                <div class="col">
                    <div class="card border-light border-1 d-flex justify-content-center p-4">
                        <div class="card-body">
                            <div class="bs-icon-lg bs-icon-rounded bs-icon-secondary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-4 bs-icon" style="background: #8D5240;"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-school" style="color: #03123E;">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M22 9l-10 -4l-10 4l10 4l10 -4v6"></path>
                                    <path d="M6 10.6v5.4a6 3 0 0 0 12 0v-5.4"></path>
                                </svg></div>
                            <div>
                                <h4 class="fw-bold">Contribute&nbsp;</h4>
                                <p class="text-muted">You can contribute relevant course materials to a centralized repository...</p><button class="btn btn-sm px-0" type="button">Learn More&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right">
                                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
                                    </svg><br></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card border-light border-1 d-flex justify-content-center p-4">
                        <div class="card-body">
                            <div class="bs-icon-lg bs-icon-rounded bs-icon-secondary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-4 bs-icon" style="background: #8D5240;"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-school" style="color: #03123E;">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M22 9l-10 -4l-10 4l10 4l10 -4v6"></path>
                                    <path d="M6 10.6v5.4a6 3 0 0 0 12 0v-5.4"></path>
                                </svg></div>
                            <div>
                                <h4 class="fw-bold">Access</h4>
                                <p class="text-muted">Gain access to our centralized repository of course materials and past questions...</p><button class="btn btn-sm px-0" type="button">Learn More&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right">
                                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
                                    </svg><br></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card border-light border-1 d-flex justify-content-center p-4">
                        <div class="card-body">
                            <div class="bs-icon-lg bs-icon-rounded bs-icon-secondary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-4 bs-icon" style="background: #8D5240;"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-school" style="color: #03123E;">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M22 9l-10 -4l-10 4l10 4l10 -4v6"></path>
                                    <path d="M6 10.6v5.4a6 3 0 0 0 12 0v-5.4"></path>
                                </svg></div>
                            <div>
                                <h4 class="fw-bold">Verify</h4>
                                <p class="text-muted">Seamlessly verify your departmental fee payment and generate your receipt...</p><button class="btn btn-sm px-0" type="button">Learn More&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right">
                                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
                                    </svg><br></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock section1 %}

    {% block section2 %}
    <section>
        <div class="container py-4 py-xl-5" style="box-shadow: 5px 5px 10px 3px #4A524D;">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="display-6 fw-bold pb-md-4" style="color: #03123E;">Contribute essential course&nbsp;<span class="underlined" style="color: #03123E;">materials</span></h3>
                </div>
                <div class="col-md-6 col-xxl-6 pt-4">
                    <p class="text-muted mb-4"><span style="color: rgb(32, 33, 36);">By contributing your materials, you're not only helping fellow students but also fostering a collaborative learning environment within the department.</span><br><br></p>
                </div>
            </div>
        </div>
    </section>
    {% endblock section2 %}

    {% block section3 %} 
    <section>
        <div class="container py-4 py-xl-5">
            <div class="row gy-4 gy-md-0">
                <div class="col-md-6 text-center text-md-start d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                    <div><img class="rounded img-fluid fit-cover" style="min-height: 300px;" src="{% static 'img/illustrations/presentation.svg' %}" width="800"></div>
                </div>
                <div class="col">
                    <div style="max-width: 450px;">
                        <h3 class="fw-bold pb-md-4" style="color: #03123E;"><span class="underlined">Access</span>&nbsp;a centralized repository of essential course materials&nbsp;&nbsp;</h3>
                        <p class="text-muted py-4 py-md-0"><span style="color: rgb(32, 33, 36);">This initiative aims to create a centralized repository of essential course materials and past questions, ensuring that all students have easy access to the resources they need to excel academically.</span><br><br></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock section3 %}

ereceipt/main/templates/main/import_excel.html
{% extends 'index.html' %}
{% load static %}

{% block title %}Import{% endblock title %}

{% block top %} 
<ul class="navbar-nav mx-auto">
    <li class="nav-item"><a class="nav-link" href="{% url 'main:home' %}">Home</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:contribute' %}">Contribute</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:access' %}">Access</a></li>
    <li class="nav-item"><a class="nav-link active" href="{% url 'main:verify' %}">Verify</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:about' %}">About</a></li>
</ul><a class="btn btn-primary shadow" role="button" href="{% url 'main:verify' %}" style="background: #03123E;border-radius: 20px;box-shadow: 0px 0px #4A524D;">E-Receipt</a>
{% endblock top %}

{% block header  %}
    <section class="py-5 mt-5" style="padding-bottom: 10px !important;padding-top: 20px !important;padding-right: 0px;">
        <div class="container py-4 py-xl-5" style="height: 280px;">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 class="display-6 fw-bold mb-4">Import Student&nbsp;<span class="underlined">Data</span></h2>
                </div>
            </div>
        </div>
    </section>
{% endblock header  %}

{% block section1 %}
    <section class="py-4 py-xl-5" style="padding-top: 5px !important;padding-bottom: 10px !important;">
        <div class="container">
            <section class="position-relative py-4 py-xl-5" style="padding-top: 10px !important;padding-bottom: 10px !important;">
                <div class="container position-relative">
                    <div class="row d-flex justify-content-center">
                        <div class="col-md-8 col-lg-6 col-xl-5 col-xxl-4" style="width: 900px;">
                            <div class="card mb-5" style="width: 900px;height: 249.6px;margin: 0px;">
                                <div class="card-body p-sm-5">
                                    <h2 class="text-center mb-4">Data Import</h2>
                                    <form method="post" enctype="multipart/form-data" url="{% url 'main:import' %}">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <input class="form-control" type="file" name="csv_file" accept=".csv">
                                        </div>
                                        
                                        <div><button class="btn btn-primary d-block w-100" type="submit">Upload and Import</button></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </section>
{% endblock section1 %}

ereceipt/main/templates/main/receipt.html
{% load static %}
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{{ student.FullName }} Receipt</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
</head>

<body class="text-center d-flex d-md-flex flex-row justify-content-around align-items-center align-content-center align-items-md-center">
    <div class="container" style="margin-top: 100px;margin-right: 0px;margin-bottom: 0px;margin-left: 0px;min-height: 500px;padding-top: 10px;padding-right: 15px;padding-bottom: 15px;padding-left: 15px;width: 800px;box-shadow: 5px 5px 4px;background: url(&quot;{% static 'img/brands/logo_opac.png' %}&quot;) center / contain no-repeat;border-style: solid;border-bottom-style: none;">
        <div class="row" style="border-style: none;border-bottom-style: dashed;">
            <div class="col">
                <div class="row" style="padding: 3px;">
                    <div class="col text-center align-self-center" style="width: 500px;border-style: none;border-bottom-style: none;">
                        <h5><strong>REDEEMERS UNIVERSITY ACCOUNTING STUDENT ASSOCIATION</strong></h5>
                        <h3><strong>(RUNASA)</strong></h3>
                        <h3>Payment Receipt</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col" style="margin-top: 15px;line-height: 45px;">
                <h5 style="text-align: center;line-height: 50px;">This is to certify that <strong>{{ student.FullName }} </strong>in <strong>{{ student.Level}}&nbsp;</strong>Level with matric number <strong>{{ student.MatricNo }}</strong> paid N&nbsp;<strong>{{ student.Amount }}</strong>&nbsp;departmental fee for the 2023/2024 Academic Session.</h5>
                <h5></h5>
            </div>
        </div>
        <div class="row d-md-flex justify-content-md-center" style="text-align: center;">
            <div class="col"><img width="100" height="80" style="border-bottom-style: none;" src="{% static 'img/brands/president_sig_tsp.png' %}">
                <p style="margin-bottom: 1px;">Abatan Moyosoreoluwa O.</p><em>President</em>
            </div>
            <div class="col align-items-center align-content-center" style="text-align: center;padding-top: 50px;">
                <p>Date: <strong>{{ student.Date }}</strong></p>
                <p>Receipt No: <strong>{{ student.ReceiptNo }}</strong></p>
            </div>
            <div class="col"><img width="100" height="80" style="border-bottom-style: none;" src="{% static 'img/brands/finSec_sig_tsp.png' %}">
                <p style="margin-bottom: 1px;">Adetunji Feyifunmi</p><em>Financial Secretary</em>
            </div>
        </div>
    </div>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/startup-modern.js' %}"></script>
</body>

</html>

ereceipt/main/templates/main/verify.html
{% extends 'index.html' %}
{% load static %}

{% block title %}Verify{% endblock title %}

{% block top %} 
<ul class="navbar-nav mx-auto">
    <li class="nav-item"><a class="nav-link" href="{% url 'main:home' %}">Home</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:contribute' %}">Contribute</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:access' %}">Access</a></li>
    <li class="nav-item"><a class="nav-link active" href="{% url 'main:verify' %}">Verify</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:about' %}">About</a></li>
</ul><a class="btn btn-primary shadow" role="button" href="{% url 'main:verify' %}" style="background: #03123E;border-radius: 20px;box-shadow: 0px 0px #4A524D;">E-Receipt</a>
{% endblock top %}

{% block header  %}
    <section class="py-5 mt-5" style="padding-bottom: 10px !important;padding-top: 20px !important;padding-right: 0px;">
        <div class="container py-4 py-xl-5" style="height: 280px;">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 class="display-6 fw-bold mb-4">Generate deparmentel fee payment&nbsp;<span class="underlined">receipt</span></h2>
                    <p class="text-muted">Once your payment has been confirmed and verified, you can generate your e-receipt. Remember to save/print your receipt for reference purpose.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock header  %}

{% block section1 %}
    <section class="py-4 py-xl-5" style="padding-top: 5px !important;padding-bottom: 10px !important;">
        <div class="container">
            <section class="position-relative py-4 py-xl-5" style="padding-top: 10px !important;padding-bottom: 10px !important;">
                <div class="container position-relative">
                    <div class="row d-flex justify-content-center">
                        <div class="col-md-8 col-lg-6 col-xl-5 col-xxl-4" style="width: 900px;">
                            <div class="card mb-5" style="width: 900px;height: 249.6px;margin: 0px;">
                                {% if messages %}
                                    {% for message in messages %}
                                        <h5 class="text-center {{ messages.tags }} animate__animated
                                        animate__fadeIn animate__delay-3s">{{ message }}</h5>
                                    {% endfor %}
                                {% endif %}
                                <div class="card-body p-sm-5">
                                    <h2 class="text-center mb-4">E-Receipt</h2>
                                    <form method="post" url="{% url 'main:verify' %}" target="_blank">
                                        {% csrf_token %}
                                        <div class="mb-3"><input class="form-control" type="text" id="MatricNo" name="MatricNo" placeholder="Matric No/Jamb No"></div>
                                        <div class="mb-3"></div>
                                        <div class="mb-3"></div>
                                        <div><button class="btn btn-primary d-block w-100" type="submit">Check</button></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </section>
{% endblock section1 %}

{% block extrascript %}
    <script>
        var m = document.getElementsByClassName("animate__fadeIn");  // Return an array
    
        setTimeout(function(){
        if (m && m.length) {
            m[0].classList.add('animate__fadeOut');
        }
        }, 5000);
    </script>
    {% endblock extrascript %}