ereceipt/administrator/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView as logout_view
from . import views

urlpatterns = [
    path('administrator/', include(([
            path('', views.login_redirect, name="landing"),
            path('login/', views.login_view, name="login"),
            path('logout/', logout_view.as_view(), name="logout"),
            path('dashboard/', views.dashboard, name='dashboard'),
            path('dashboard/students', views.StudentsListView.as_view(), name='students'),
            path('verify/student/<int:student_id>', views.verify, name='verify'),
            path('search/matric', views.search, name='search'),
        ], 'cares'), namespace='administrator'))
]

ereceipt/ereceipt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('administrator.urls')),
]

ereceipt/main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include(([
        path('', views.home, name='home'),
        path('contribute', views.contribute, name="contribute"),
        path('access', views.access, name="access"),
        path('about', views.about, name="about"),
        path('verify', views.verify, name="verify"),
        path('receipt/<int:student_id>', views.receipt, name="receipt"),
        # path('import', views.import_excel, name="import"),
    ], 'ereceipt'), namespace='main')),
]

ereceipt/administrator/models.py
from django.db import models

# Create your models here.

ereceipt/administrator/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.forms import widgets
from main.models import User, Student, PAYMENT_STATUS


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter Username...",
                "class": "shadow form-control form-control-user"
            }
        ))

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "shadow form-control form-control-user"
            }
        ))


class StudentVerificationForm(forms.ModelForm):
    Paid = forms.ChoiceField(
        choices=PAYMENT_STATUS,
        widget=forms.Select(
            attrs={
                'class': 'form-control form-control-select',
                'style': "border-radius: 10rem;padding: 0.5rem 0.5rem;",
                'placeholder': " Payment Status",
            }
        ))
    
    Amount = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control form-control-user",
                'placeholder': " Amount Paid",
            }
        ))
    Date = forms.DateField(
        widget=forms.NumberInput(
            attrs={
                'type': 'date',
                'class': 'form-control form-control-select',
                'placeholder': " Select Payment Date",
                'style': "border-radius: 10rem;padding: 0.5rem 0.5rem;",
            }
        ))

    class Meta:
        model = Student
        fields = ('Paid', 'Amount', 'Date')


# class ProfileInfoUpdateForm(forms.ModelForm):
#     username = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control form-control-user",
#             }
#         ))
#     first_name = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control form-control-user",
#             }
#         ))
#     last_name = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control form-control-user",
#             }
#         ))
#     email = forms.EmailField(
#         widget=forms.EmailInput(
#             attrs={
#                 "class": "form-control form-control-user",
#             }
#         ))

#     class Meta:
#         model = User
#         fields = ('username', 'email', 'first_name', 'last_name')

ereceipt/administrator/views.py
import random, string
import numpy as np
import pandas as pd
from django.contrib import messages
from django.utils import timezone
from django.views.generic import ListView
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

########################

from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from .forms import *
from main.models import Student


# Create your views here.
def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if user.user_type == 1:
                    return redirect("administrator:dashboard")
                    # return HttpResponse("ADMIN DASHBOARD")
                elif user.user_type == 2:
                    messages.success(request, 'STUDENT SUCCESSFUL LOGIN')
                    # return redirect("agents:dashboard")
                    return HttpResponse("STUDENT DASHBOARD")
                else:
                    msg = 'Something Went Wrong'
                    HttpResponseRedirect('landing')
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "administrator/login.html", {"form": form, "msg": msg})


def login_redirect(request):
    return HttpResponseRedirect('login')

@login_required
def dashboard(request):
    # Check if there are students in the database
    check = len(Student.objects.all())
    if check > 0:
        # Get all rentals
        allstudents = Student.objects.all()
        # Create DataFrame of all Rental Agreements
        df = pd.DataFrame.from_records(allstudents.values())

        # Convert date ending and date started to datetime datatype
        df[['Date']] = df[['Date']].apply(pd.to_datetime)
        df[['Level']] = df[['Level']].apply(pd.to_numeric)


        # Get values 
        all_students,_ = df.shape
        amount_paid = df['Amount'].sum()
        
        df_paid = df[df['Paid']==1] # Data of students that have paid
        df_unpaid = df[df['Paid']==0] # Data of students that have not paid
        no_paid, _ = df_paid.shape # Number of students that have paid
        no_unpaid, _ = df_unpaid.shape # Number of students that have not paid
        perc_paid = np.round((no_paid/all_students)*100,2)

        # Convert the 

        """
        Values for Payment Progress
        
        """
        # 400 Level
        df_400 = df[df['Level']==400]
        df_400_paid = df_400[df_400['Paid']==1]
        no_400,_ = df_400.shape
        no_400_paid,_ = df_400_paid.shape
        if no_400 > 0:
            perc_400 = np.round((no_400_paid/no_400 * 100), 2)
        else:
            perc_400 = 0

        # 300 Level
        df_300 = df[df['Level']==300]
        df_300_paid = df_300[df_300['Paid']==1]
        no_300,_ = df_300.shape
        no_300_paid,_ = df_300_paid.shape
        if no_300 > 0:
            perc_300 = np.round((no_300_paid/no_300 * 100), 2)
        else:
            perc_300 = 0

        # 200 Level
        df_200 = df[df['Level']==200]
        df_200_paid = df_200[df_200['Paid']==1]
        no_200,_ = df_200.shape
        no_200_paid,_ = df_200_paid.shape
        if no_200 > 0:
            perc_200 = np.round((no_200_paid/no_200 * 100), 2)
        else:
            perc_200 = 0

        # 100 Level
        df_100 = df[df['Level']==100]
        df_100_paid = df_100[df_100['Paid']==1]
        no_100,_ = df_100.shape
        no_100_paid,_ = df_100_paid.shape
        if no_100 > 0:
            perc_100 = np.round((no_100_paid/no_100 * 100), 2)
        else:
            perc_100 = 0




    context = {
        'all_students':all_students,
        'amount_paid':amount_paid,
        'perc_paid':perc_paid,
        'no_unpaid': no_unpaid,
        'perc_400': perc_400,
        'perc_300': perc_300,
        'perc_200': perc_200,
        'perc_100': perc_100,
    }

    return render(request, 'administrator/dashboard/dashboard.html', context) 

class StudentsListView(ListView):
    model = Student
    template_name = "administrator/dashboard/students.html"
    context_object_name = "students"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.user_type == 1:
            # Get all students
            queryset = Student.objects.all()
        return queryset

    # extra_context = {
    #     'alertCount': alert()[1],
    #     'alerts': alert()[0],
    # }
    ordering = ['-id']
    paginate_by = 10

@login_required
def verify(request, student_id):
    if student_id is None:
        messages.error(request, 'No Student Selected')
        return HttpResponseRedirect(reverse("administrator:students"))
    else:
        try:
            student = Student.objects.get(id=student_id)
        except ObjectDoesNotExist:
            messages.error(request, 'Something Went Wrong')
            return HttpResponseRedirect(reverse("administrator:students"))
    
    form = StudentVerificationForm(request.POST or None)
    
    # Check for form submission
    if request.method == "POST":
        # Check form submission
        if form.is_valid():
            payment_date = form.cleaned_data.get("Date")
            amount = form.cleaned_data.get("Amount")
            status = form.cleaned_data.get("Paid")

            # Generate Unique ReceiptNo
            #############################
            # Randomly Choose Letters for adding to code
            def gencode():
                char1 = random.choice(string.ascii_uppercase)
                char2 = random.choice(string.ascii_lowercase)
                char3 = random.choice(string.ascii_letters)
                char4 = random.choice('1234567890')

                return f"RUNASA/2023/{student_id}/{char1}{char2}{char4}{char3}"

            #############################
            rcn = gencode()
            receipt_no = rcn
            while Student.objects.filter(ReceiptNo=rcn):
                rcn = gencode()
                if not Student.objects.filter(receipt_no=gencode):
                    receipt_no = gencode
            
            # Update the Student Record
            student.Paid, student.Amount, student.Date, student.ReceiptNo = (status,amount,payment_date,receipt_no)
            student.save()
            
            messages.success(request, 'Payment Verified Successfully')
            return HttpResponseRedirect(reverse("administrator:students"))

    context = {
        'student': student,
        'form': form,
    }

    return render(request, 'administrator/dashboard/verification.html', context)


@login_required()
def search(request):
    # Default assignment for querysets
    students = None
    query = None
    count = 0

    if request.method == 'GET':
        query = request.GET.get('q')
        if query is None:
            messages.error(request, 'Empty Search')
            return HttpResponseRedirect(reverse("administrator:dashboard"))
        else:
            query_clean = query.replace(" ", "+")
            query = query.upper()
            try:
                # Filter students to get matches
                students = Student.objects.filter(MatricNo__contains=query)
                count = len(students)
            except ObjectDoesNotExist:
                messages.error(request, 'Empty Search')
                return HttpResponseRedirect(reverse("administrator:dashboard"))

    context = {
        'students': students,
        'count': count,
        'query': query,
    }

    return render(request, 'administrator/dashboard/search.html', context)
    
# @login_required
# def update(request, student_id):
#     if student_id is None:
#         messages.error(request, 'No Student Selected')
#         return HttpResponseRedirect(reverse("administrator:students"))
#     else:
#         try:
#             student = Student.objects.get(id=student_id)
#         except ObjectDoesNotExist:
#             messages.error(request, 'Something Went Wrong')
#             return HttpResponseRedirect(reverse("administrator:students"))
    
    

ereceipt/administrator/templates/administrator/dashboard/search.html
{% extends 'administrator/layouts/index.html' %}
{% load static %}

{% load static %}
{% block title%}Students{% endblock title%}
{% block header %}
<div class="container-fluid">
    <div class="d-sm-flex justify-content-between align-items-center mb-4">
        <h1 class="h3 mb-0 text-gray-800">Search Results</h1><a class="btn btn-primary btn-sm shadow-sm d-none d-sm-inline-block disabled" role="button" href="#" style="background: #8D5240;"><i class="fas fa-download text-white-50 fa-sm"></i> Generate Report</a>
    </div>
    <p class="mb-4">Below are the results from search...</p>
</div>
{% endblock header %}

{% block row1 %}
{% if count == 0 %}
    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h4 class="m-0 font-weight-bold text-primary text-center">No Results Found</h4>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                {% if messages %}
                    {% for message in messages %}
                        <h5 class="text-center {{ messages.tags }} animate__animated animate__fadeIn animate__delay-3s">{{ message }}</h5>
                    {% endfor %}
                  {% endif %}
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Your Searched for: {{ query }}</h6>
            </div>
            <div class="card-block tab-icon">
               <ul class="nav nav-tabs md-tabs " role="tablist">
                   <li class="nav-item">
                        <form action="{% url 'administrator:search' %}" method="GET">
                                <input type="text" name="q" hidden="true" class="form-control bg-light border-0 small" placeholder="Search for..."
                                    aria-label="Search" aria-describedby="basic-addon2" value="{{ query }}">
                                <button class="nav-link active text-primary" type="submit"><i
                                        class="icofont icofont-ui-user "></i>All Results</button>
                                <div class="slide"></div>
                        </form>
                    </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content card-block">
                    <div class="tab-pane active" id="all" role="tabpanel">
                      <div class="card">
                        <div class="card-header">
                          <h5>Students</h5>
                        </div>
                        <div class="card-block">
                            {% if count > 0 %}
                                <div class="table-responsive">
                                    <table class="table table-outline table-hover" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>Full Name</th>
                                                <th>Matric Number</th>
                                                <th>Level</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for student in students %}
                                                <tr>
                                                    <td>{{ student.FullName.upper }}</td>
                                                    <td>{{ student.MatricNo }}</td>
                                                    <td>{{ student.Level }}</td>
                                                    {% if student.Paid == 1 %}
                                                        <td><span class="btn btn-user btn-dark btn-sm disabled"
                                                           href="">Already Verified</span></td>
                                                    {% else %}
                                                        <td><a class="btn btn-user btn-secondary btn-sm"
                                                            href="{% url 'administrator:verify' student.id %}">Verify</a></td>
                                                    {% endif %}
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}
                            <h4 class="m-0 font-weight-bold text-primary text-center">No Match</h4>
                            {% endif %}
                        </div>
                      </div>
                    </div>
                </div>
            </div>
    </div>
{% endif %}
{% endblock row1 %}
</div>
        

ereceipt/administrator/templates/administrator/dashboard/students.html
{% extends 'administrator/layouts/index.html' %}
{% load static %}

{% load static %}
{% block title%}Students{% endblock title%}
{% block header %}
<div class="d-sm-flex justify-content-between align-items-center mb-4">
    <h1 class="h3 mb-0 text-gray-800">Students</h1><a class="btn btn-primary btn-sm shadow-sm d-none d-sm-inline-block disabled" role="button" href="#" style="background: #8D5240;"><i class="fas fa-download text-white-50 fa-sm"></i> Generate Report</a>
</div>
<p class="mb-4">This is a database of the currently recorded students in the accounting department at all levels</p>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="text-primary m-0 font-weight-bold" style="color: #8D5240 !important;">All Students</h6>
        {% if messages %}
            {% for message in messages %}
                <h5 class="text-center {{ messages.tags }} animate__animated
                animate__fadeIn animate__delay-3s">{{ message }}</h5>
            {% endfor %}
        {% endif %}
    </div>
    <div class="card-body">
        {% if students %}
            <div class="table-responsive">
                <table class="table table-outline table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Full Name</th>
                            <th>Matric No</th>
                            <th>Level</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in students %}
                        <tr>
                            <td>{{ student.FullName.upper }}</td>
                            <td>{{ student.MatricNo}} </td>
                            <td>{{ student.Level }}</td> 
                            {% if student.Paid == 0 %}
                                <td><a class="btn btn-primary btn-sm" style="border-radius: 20px !important" 
                                    href="{% url 'administrator:verify' student.id %}">Verify</a></td>
                            {% else %}
                            <td><span class="btn btn-dark btn-sm" href="">Already Verified</span></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="text-right m-r-20">
                    {% if is_paginated %}
                        {% if page_obj.has_previous %}
                            <a class="badge badge-inverse-primary" href="?page=1" data-toggle="tooltip" data-placement="top"
                                data-trigger="hover" title="First Page">First</a>
                            <a class="badge badge-inverse-primary" href="?page={{ page_obj.previous_page_number }}"
                                data-toggle="tooltip" data-placement="top" data-trigger="hover"
                                title="Previous Page">Previous</a>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                            <a class="badge badge-primary" style="color: white !important;" href="?page={{ num }}"
                                data-toggle="tooltip" data-placement="top" data-trigger="hover"
                                title="Page {{ num }}">{{ num }}</a>
                            {% elif num > page_obj.number|add:'-4' and num < page_obj.number|add:'4' %}
                            <a class="badge badge-inverse-primary" href="?page={{ num }}"
                                data-toggle="tooltip" data-placement="top" data-trigger="hover"
                                title="Page {{ num }}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <a class="badge badge-inverse-primary" href="?page={{ page_obj.next_page_number }}"
                                data-toggle="tooltip" data-placement="top" data-trigger="hover" title="Next Page">Next</a>
                            <a class="badge badge-inverse-primary" href="?page={{ page_obj.paginator.num_pages }}"
                                data-toggle="tooltip" data-placement="top" data-trigger="hover" title="Last Page">Last</a>
                        {% endif %}

                    {% endif %}
                    <a href="{% url 'administrator:dashboard' %}" class="b-b-primary text-primary">Back To Dashboard</a>
                </div>
            </div>
        {% else %}
        <h6 class="m-0 font-weight-bold text-primary text-center">
                    No Student Record</h6>
        {% endif %}
        
    </div>
</div>
{% endblock header %}
                

ereceipt/administrator/templates/administrator/dashboard/verification.html
{% extends 'administrator/layouts/index.html' %}
{% load static %}

{% load static %}
{% block title%}Students{% endblock title%}
{% block header %}
<div class="container-fluid">
    <div class="d-sm-flex justify-content-between align-items-center mb-4">
        <h1 class="h3 mb-0 text-gray-800">Students</h1><a class="btn btn-primary btn-sm shadow-sm d-none d-sm-inline-block disabled" role="button" href="#" style="background: #8D5240;"><i class="fas fa-download text-white-50 fa-sm"></i> Generate Report</a>
    </div>
    <p class="mb-4">Use this form to verify that the students payment have been received in the account and the student can generate an e-receipt. An automatic receipt number will be attached to the student once you submit the form.</p>
</div>
{% endblock header %}

{% block row1 %}
<div class="row">
    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                 <div class="d-sm-flex align-items-center justify-content-between mb-0">
                    <h6 class="m-0 font-weight-bold text-primary">Student Information</h6>
                </div>
            </div>
            <div class="card-body">
                <div class="p-5">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="h6 mb-0 font-weight-bold text-gray-600">
                                Full Name: {{ student.FullName.upper }}
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="h6 mb-0 font-weight-bold text-gray-600">
                                Matric Number: {{ student.MatricNo }}
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="h6 mb-0 font-weight-bold text-gray-600">
                                Level: {{ student.Level }}
                            </div>
                        </div>
                    </div>
                    <hr>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock row1 %}

{% block row2 %}
<div class="row">
    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            {% if messages %}
                {% for message in messages %}
                    <h5 class="text-center {{ messages.tags }} animate__animated
                    animate__fadeIn animate__delay-3s">{{ message }}</h5>
                {% endfor %}
            {% endif %}
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Verify Student Payment</h6>
            </div>
            <div class="card-body">
                <div class="p-5">
                    <form action="{% url 'administrator:verify' student.id %}" class="user" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <span class="form-bar"></span>
                                    <label class="float-label text-primary">Payment Status</label>
                                    {{ form.Paid }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <span class="form-bar"></span>
                                    <label class="float-label text-primary">Amount Paid</label>
                                    {{ form.Amount}}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <span class="form-bar"></span>
                                    <label class="float-label text-primary">Payment Date</label>
                                    {{ form.Date }}
                                </div>
                            </div>
                            <div class="col-sm-6">

                            </div>
                        </div>
                        <hr>

                        <button class="btn btn-primary btn-user btn-block" type="submit">Complete Verification</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock row2 %}
</div>
        