ereceipt/administrator/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView as logout_view
from . import views

urlpatterns = [
    path('administrator/', include(([
            path('', views.login_redirect, name="landing"),
            path('login/', views.login_view, name="login"),
            path('logout/', logout_view.as_view(), name="logout"),
            path('dashboard/', views.dashboard, name='dashboard'),
            path('dashboard/students', views.StudentsListView.as_view(), name='students'),
            path('verify/student/<int:student_id>', views.verify, name='verify'),
            path('search/matric', views.search, name='search'),
        ], 'cares'), namespace='administrator'))
]

ereceipt/ereceipt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('administrator.urls')),
]

ereceipt/main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include(([
        path('', views.home, name='home'),
        path('contribute', views.contribute, name="contribute"),
        path('access', views.access, name="access"),
        path('about', views.about, name="about"),
        path('verify', views.verify, name="verify"),
        path('receipt/<int:student_id>', views.receipt, name="receipt"),
        # path('import', views.import_excel, name="import"),
    ], 'ereceipt'), namespace='main')),
]

ereceipt/administrator/models.py
from django.db import models

# Create your models here.

ereceipt/administrator/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.forms import widgets
from main.models import User, Student, PAYMENT_STATUS


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter Username...",
                "class": "shadow form-control form-control-user"
            }
        ))

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "shadow form-control form-control-user"
            }
        ))


class StudentVerificationForm(forms.ModelForm):
    Paid = forms.ChoiceField(
        choices=PAYMENT_STATUS,
        widget=forms.Select(
            attrs={
                'class': 'form-control form-control-select',
                'style': "border-radius: 10rem;padding: 0.5rem 0.5rem;",
                'placeholder': " Payment Status",
            }
        ))
    
    Amount = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control form-control-user",
                'placeholder': " Amount Paid",
            }
        ))
    Date = forms.DateField(
        widget=forms.NumberInput(
            attrs={
                'type': 'date',
                'class': 'form-control form-control-select',
                'placeholder': " Select Payment Date",
                'style': "border-radius: 10rem;padding: 0.5rem 0.5rem;",
            }
        ))

    class Meta:
        model = Student
        fields = ('Paid', 'Amount', 'Date')


# class ProfileInfoUpdateForm(forms.ModelForm):
#     username = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control form-control-user",
#             }
#         ))
#     first_name = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control form-control-user",
#             }
#         ))
#     last_name = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control form-control-user",
#             }
#         ))
#     email = forms.EmailField(
#         widget=forms.EmailInput(
#             attrs={
#                 "class": "form-control form-control-user",
#             }
#         ))

#     class Meta:
#         model = User
#         fields = ('username', 'email', 'first_name', 'last_name')

ereceipt/administrator/views.py
import random, string
import numpy as np
import pandas as pd
from django.contrib import messages
from django.utils import timezone
from django.views.generic import ListView
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

########################

from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from .forms import *
from main.models import Student


# Create your views here.
def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if user.user_type == 1:
                    return redirect("administrator:dashboard")
                    # return HttpResponse("ADMIN DASHBOARD")
                elif user.user_type == 2:
                    messages.success(request, 'STUDENT SUCCESSFUL LOGIN')
                    # return redirect("agents:dashboard")
                    return HttpResponse("STUDENT DASHBOARD")
                else:
                    msg = 'Something Went Wrong'
                    HttpResponseRedirect('landing')
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "administrator/login.html", {"form": form, "msg": msg})


def login_redirect(request):
    return HttpResponseRedirect('login')

@login_required
def dashboard(request):
    # Check if there are students in the database
    check = len(Student.objects.all())
    if check > 0:
        # Get all rentals
        allstudents = Student.objects.all()
        # Create DataFrame of all Rental Agreements
        df = pd.DataFrame.from_records(allstudents.values())

        # Convert date ending and date started to datetime datatype
        df[['Date']] = df[['Date']].apply(pd.to_datetime)
        df[['Level']] = df[['Level']].apply(pd.to_numeric)


        # Get values 
        all_students,_ = df.shape
        amount_paid = df['Amount'].sum()
        
        df_paid = df[df['Paid']==1] # Data of students that have paid
        df_unpaid = df[df['Paid']==0] # Data of students that have not paid
        no_paid, _ = df_paid.shape # Number of students that have paid
        no_unpaid, _ = df_unpaid.shape # Number of students that have not paid
        perc_paid = np.round((no_paid/all_students)*100,2)

        # Convert the 

        """
        Values for Payment Progress
        
        """
        # 400 Level
        df_400 = df[df['Level']==400]
        df_400_paid = df_400[df_400['Paid']==1]
        no_400,_ = df_400.shape
        no_400_paid,_ = df_400_paid.shape
        if no_400 > 0:
            perc_400 = np.round((no_400_paid/no_400 * 100), 2)
        else:
            perc_400 = 0

        # 300 Level
        df_300 = df[df['Level']==300]
        df_300_paid = df_300[df_300['Paid']==1]
        no_300,_ = df_300.shape
        no_300_paid,_ = df_300_paid.shape
        if no_300 > 0:
            perc_300 = np.round((no_300_paid/no_300 * 100), 2)
        else:
            perc_300 = 0

        # 200 Level
        df_200 = df[df['Level']==200]
        df_200_paid = df_200[df_200['Paid']==1]
        no_200,_ = df_200.shape
        no_200_paid,_ = df_200_paid.shape
        if no_200 > 0:
            perc_200 = np.round((no_200_paid/no_200 * 100), 2)
        else:
            perc_200 = 0

        # 100 Level
        df_100 = df[df['Level']==100]
        df_100_paid = df_100[df_100['Paid']==1]
        no_100,_ = df_100.shape
        no_100_paid,_ = df_100_paid.shape
        if no_100 > 0:
            perc_100 = np.round((no_100_paid/no_100 * 100), 2)
        else:
            perc_100 = 0




    context = {
        'all_students':all_students,
        'amount_paid':amount_paid,
        'perc_paid':perc_paid,
        'no_unpaid': no_unpaid,
        'perc_400': perc_400,
        'perc_300': perc_300,
        'perc_200': perc_200,
        'perc_100': perc_100,
    }

    return render(request, 'administrator/dashboard/dashboard.html', context) 

class StudentsListView(ListView):
    model = Student
    template_name = "administrator/dashboard/students.html"
    context_object_name = "students"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.user_type == 1:
            # Get all students
            queryset = Student.objects.all()
        return queryset

    # extra_context = {
    #     'alertCount': alert()[1],
    #     'alerts': alert()[0],
    # }
    ordering = ['-id']
    paginate_by = 10

@login_required
def verify(request, student_id):
    if student_id is None:
        messages.error(request, 'No Student Selected')
        return HttpResponseRedirect(reverse("administrator:students"))
    else:
        try:
            student = Student.objects.get(id=student_id)
        except ObjectDoesNotExist:
            messages.error(request, 'Something Went Wrong')
            return HttpResponseRedirect(reverse("administrator:students"))
    
    form = StudentVerificationForm(request.POST or None)
    
    # Check for form submission
    if request.method == "POST":
        # Check form submission
        if form.is_valid():
            payment_date = form.cleaned_data.get("Date")
            amount = form.cleaned_data.get("Amount")
            status = form.cleaned_data.get("Paid")

            # Generate Unique ReceiptNo
            #############################
            # Randomly Choose Letters for adding to code
            def gencode():
                char1 = random.choice(string.ascii_uppercase)
                char2 = random.choice(string.ascii_lowercase)
                char3 = random.choice(string.ascii_letters)
                char4 = random.choice('1234567890')

                return f"RUNASA/2023/{student_id}/{char1}{char2}{char4}{char3}"

            #############################
            rcn = gencode()
            receipt_no = rcn
            while Student.objects.filter(ReceiptNo=rcn):
                rcn = gencode()
                if not Student.objects.filter(receipt_no=gencode):
                    receipt_no = gencode
            
            # Update the Student Record
            student.Paid, student.Amount, student.Date, student.ReceiptNo = (status,amount,payment_date,receipt_no)
            student.save()
            
            messages.success(request, 'Payment Verified Successfully')
            return HttpResponseRedirect(reverse("administrator:students"))

    context = {
        'student': student,
        'form': form,
    }

    return render(request, 'administrator/dashboard/verification.html', context)


@login_required()
def search(request):
    # Default assignment for querysets
    students = None
    query = None
    count = 0

    if request.method == 'GET':
        query = request.GET.get('q')
        if query is None:
            messages.error(request, 'Empty Search')
            return HttpResponseRedirect(reverse("administrator:dashboard"))
        else:
            query_clean = query.replace(" ", "+")
            query = query.upper()
            try:
                # Filter students to get matches
                students = Student.objects.filter(MatricNo__contains=query)
                count = len(students)
            except ObjectDoesNotExist:
                messages.error(request, 'Empty Search')
                return HttpResponseRedirect(reverse("administrator:dashboard"))

    context = {
        'students': students,
        'count': count,
        'query': query,
    }

    return render(request, 'administrator/dashboard/search.html', context)
    
# @login_required
# def update(request, student_id):
#     if student_id is None:
#         messages.error(request, 'No Student Selected')
#         return HttpResponseRedirect(reverse("administrator:students"))
#     else:
#         try:
#             student = Student.objects.get(id=student_id)
#         except ObjectDoesNotExist:
#             messages.error(request, 'Something Went Wrong')
#             return HttpResponseRedirect(reverse("administrator:students"))
    
    

ereceipt/administrator/templates/administrator/layouts/index.html
{% load static %}
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>C.A.R.E.S - {% block title%}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'administrator/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'administrator/css/Font%20Awesome%205%20Brands.css' %}">
    <link rel="stylesheet" href="{% static 'administrator/css/Font%20Awesome%205%20Free.css' %}">
    <link rel="stylesheet" href="{% static 'administrator/fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'administrator/css/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'administrator/css/vendor/datatables/dataTables.bootstrap4.min.css' %}">
</head>

<body id="page-top">
    <div id="wrapper"><ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

            
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'administrator:dashboard' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <img src="{% static 'img/brands/logo.png' %}" alt="RUNASA Logo" style="max-width:80px; margin-right:-30px">
                </div>
                <div class="sidebar-brand-text mx-3">C.A.R.E.S <sup>v1</sup></div>
            </a>

            
            <hr class="sidebar-divider my-0">

            
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'administrator:dashboard' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            
            <hr class="sidebar-divider">

            
            <div class="sidebar-heading">
                Departmental Fees
            </div>
            
            {% comment %} <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-check-circle"></i>
                    <span>Payments</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Verification </h6>
                        <a class="collapse-item" href="">New</a>
                        <a class="collapse-item disabled" href="">Edit</a>
                    </div>
                </div>
            </li> {% endcomment %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'administrator:students' %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Students</span></a>
            </li>

            
            <hr class="sidebar-divider d-none d-md-block">

            
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="bg-white shadow navbar navbar-expand navbar-light topbar mb-4 static-top"><button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop"><i class="fas fa-bars"></i></button>
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" 
                    action="{% url 'administrator:search' %}" method="GET">
                        <div class="input-group">
                            <input class="bg-light border-0 form-control form-control small" 
                            type="text" name="q" aria-describedby="basic-addon2" aria-label="Search" placeholder="Search Matric Number">
                            <div class="input-group-text input-group-append">
                                <button class="btn btn-primary" type="submit" style="background: #8D5240;">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                    
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search" action="{% url 'administrator:search' %}" method="GET" >
                                    <div class="input-group">
                                        <input type="text" name="q" class="form-control bg-light border-0 small" placeholder="Search for..."
                                        aria-label="Search" aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="submit">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-bell fa-fw"></i>
                                
                                <span class="badge badge-danger badge-counter">0</span>
                            </a> 
                        </li>


                        <div class="topbar-divider d-none d-sm-block"></div>

                        
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.first_name}} {{ request.user.last_name}}</span>
                                <img class="img-profile rounded-circle" src="{% static 'administrator/img/undraw_profile.svg' %}">
                            </a>
                            
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>
                </nav>
                <div class="container-fluid">
                    {% block header %}{% endblock header %}
                   
                    {% block row1 %}{% endblock row1 %}
                    
                    {% block row2 %}{% endblock row2 %}
                </div>
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Copyright © RUNASA 2023-2024</span></div>
                </div>
            </footer>
        </div>
    </div><a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
    <div class="modal fade" role="dialog" tabindex="-1" id="logoutModal" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5><button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body"><span>Select "Logout" below if you are ready to end your current session.</span></div>
                <div class="modal-footer"><button class="btn btn-secondary" data-dismiss="modal" type="button">Cancel</button><a class="btn btn-primary" role="button" href="{% url 'administrator:logout' %}">Logout</a></div>
            </div>
        </div>
    </div>
    <script src="{% static 'administrator/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'administrator/js/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'administrator/js/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'administrator/js/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'administrator/js/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'administrator/js/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'administrator/js/js/sb-admin-2.min.js' %}"></script>
    <script src="{% static 'administrator/js/vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'administrator/js/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'administrator/js/js/demo/chart-pie-demo.js' %}"></script>
    <script src="{% static 'administrator/js/js/demo/chart-bar-demo.js' %}"></script>
    <script src="{% static 'administrator/js/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'administrator/js/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'administrator/js/js/demo/datatables-demo.js' %}"></script>
</body>

</html>